### ISSUE TITLE
[ExternalLinksTest][][jcommune.webdriver.SeleniumSessionListener] - TEST FAIL: Invalid selectors

### ISSUE THREAD

**Issue by baranovRP** [jtalks-org/functional-tests#70]
[2015-07-23 22:43:50][INFO][ExternalLinksTest][][jcommune.webdriver.SeleniumSessionListener] - TEST FAIL [time on video 01:00:29] >>>

org.openqa.selenium.WebDriverException: Invalid selectors: [id^=big-screen-external-link]
Command duration or timeout: 218 milliseconds
Build info: version: '2.35.0', revision: '8df0c6bedf70ff9f22c647788f9fe9c8d22210e2', time: '2013-08-17 12:46:41'
System info: os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_51'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{webdriver.remote.sessionid=54accae9-5335-4fd7-9fa3-df06a6fe6abc, browserName=htmlunit, javascriptEnabled=true, version=, cssSelectorsEnabled=true, max-duration=10800, platform=ANY}]
Session ID: 54accae9-5335-4fd7-9fa3-df06a6fe6abc
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
  at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:191)
  at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
  at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:332)
  at org.openqa.selenium.remote.RemoteWebDriver.findElementsByCssSelector(RemoteWebDriver.java:400)
  at org.openqa.selenium.By$ByCssSelector.findElements(By.java:417)
  at org.openqa.selenium.support.pagefactory.ByAll.findElements(ByAll.java:59)
  at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:295)
  at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElements(DefaultElementLocator.java:75)
  at org.openqa.selenium.support.pagefactory.internal.LocatingElementListHandler.invoke(LocatingElementListHandler.java:35)
  at com.sun.proxy.$Proxy11.iterator(Unknown Source)
  at org.jtalks.tests.jcommune.webdriver.entity.externallink.ExternalLink.fromForm(ExternalLink.java:35)
  at org.jtalks.tests.jcommune.webdriver.action.ExternalLinks.assertLinkVisible(ExternalLinks.java:68)
  at org.jtalks.tests.jcommune.ExternalLinksTest.emptyHintShouldPassValidation(ExternalLinksTest.java:114)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
  at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
  at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
  at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  at org.testng.TestRunner.privateRun(TestRunner.java:758)
  at org.testng.TestRunner.run(TestRunner.java:613)
  at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  at org.testng.SuiteRunner.run(SuiteRunner.java:240)
  at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
  at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
  at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
  at org.testng.TestNG.run(TestNG.java:974)
  at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
  at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
  at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
  at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:111)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: org.w3c.css.sac.CSSException: Invalid selectors: [id^=big-screen-external-link]
  at com.gargoylesoftware.htmlunit.html.DomNode.querySelectorAll(DomNode.java:1555)
  at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElementsByCssSelector(HtmlUnitDriver.java:734)
  at org.openqa.selenium.By$ByCssSelector.findElements(By.java:418)
  at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElements(HtmlUnitDriver.java:1266)
  at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElements(HtmlUnitDriver.java:404)
  at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
  at com.sun.proxy.$Proxy13.findElements(Unknown Source)
  at org.openqa.selenium.support.events.EventFiringWebDriver.findElements(EventFiringWebDriver.java:169)
  at org.openqa.selenium.remote.server.handler.FindElements.call(FindElements.java:48)
  at org.openqa.selenium.remote.server.handler.FindElements.call(FindElements.java:1)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:167)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)

**Comment by ctapobep** [comment]
This is weird since these tests pass on CI. And also the selector seems correct except though the id should be surrounded by quotes.
@baranovRP will you please try to fix it on your own and figure out why it's working on other machines?

**Comment by baranovRP** [comment]
Running locally, on Firefox, the test finished successfully.
The test falls only with default settings in pom.xml
and default values are:
Selenium WebDriver URL: [http://selenium-server.jtalks.org/wd/hub]
Capabilities [{browserName=htmlunit, version=, platform=ANY, max-duration=10800}]
As test marked as "htmlunit-incompatible" it's purely understandable why it falls. And I can make an assumption that when it's running on CI it's taken into account in configurations.
Suppose the issue can be closed
